name: Take a Screenshot

on:
  workflow_dispatch:
    inputs:
      Files:
         description: 'URL(s) or File(s) to take screenshot of (seperate by comma):'
         required: true
         default: "html/quote.html,"
  schedule:
    - cron: "59 23, * * *"

jobs:
  Screenshotter:
    runs-on: ubuntu-latest
    steps:
      - name: Check out this repo
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Installed package list
        run: apt list --installed
      - name: Install all necessary packages
        run: pip install html2image
      - name: Run the quote generator
        working-directory: ./
        run: |
         python .github/workflows/generator.py
      - name: Commit and Push
        run: |
         git config --global user.name "github-actions[bot]"
         git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
         git add -A
         git commit -m "Image updated"
         git push
